var index = require('./index');
var user = require('./user');
var component = require('./component');
var vehicle = require('./vehicle');
module.exports = function (app) {
    app.get('/', index.index);
    app.get('/user/list', user.list);
    app.post('/user/registry', user.create);
    app.post('/user/login', user.login);
    app.post('/admin/vehicle/update', vehicle.updateVehicle);
    app.get('/admin/vehicle/structure', vehicle.queryVehicle);
    app.get('/admin/vehicle/list', vehicle.listVehicle);
    app.post('/admin/component/add', component.addComponent);
    app.post('/admin/component/create', component.createComponent);
    app.get('/admin/component/list', component.listComponent);
    app.get('/admin/component/delete', component.deleteComponent);
    app.get('/admin/component/edit', component.queryComponent);
    app.post('/admin/component/update', component.updateComponent);
    app.post('/admin/component/addPicture', component.addPicture);
    app.get('/admin/component/deletePicture', component.deletePicture);
};